### ISSUE TITLE
1.5.1/11.5.1/13.1.1, 1.5.2/11.5.2 

### ISSUE THREAD

**Issue by sdg-data-canada-odd-donnees** [sdg-data-canada-odd-donnees/sdg-data-donnees-odd#280]
Data in the GIF Hub data folder.

Please note that these are preliminary figures and may still be subject to change before they are published to the public facing CDD. We would appreciate it, should this extract still be of use, that any products created with this data include language that reflect this nuance.

**Comment by catherinemichaud** [comment]
1.5.1: 

- [ ] Align chart title with radio button

**Comment by tristanmenard** [comment]
Pending further details from SME for data update.

**Comment by JulienSTC** [comment]
1.5.2:

- [ ] Update indicator to Proxy
- [ ] Add banner with new proxy name: Direct economic loss attributed to disasters in relation to gross domestic product (GDP)
- [ ] Add in comments and limitation that this is a proxy indicator that measures Direct economic loss attributed to disasters in relation to Canada's gross domestic product (GDP) rather than global GDP. 
- [ ] Update indicator name in national metadata field to the new proxy name
- [ ] Add in method of computation in the denominator field that it is "GDP in current prices"

- [ ] Same as above but in the FR page:
- [ ]
